	// screen = "screen type  | page header text | number of questions | tblhead1 | tblhead2 | screen to get results from | tab name | screen to send results to"
	// questions = "question | feedback | number of follow questions"
	// followup = "question | feedback"
	
	var screencount=5; // zero-based
	var pre_review_count = 4 // zero-based
	var body_screen = 9;
	var body_q = 1;
	var case_name = "opioids_2";
	var txt_casehistory = "Sharon is a 56 yr. old female patient who comes to your  office complaining of ongoing chronic back pain. She has known degenerative  disc disease that has been managed with physiotherapy and anti-inflammatories.  Several years ago she had been treated with short-acting oxycodone after an  acute on chronic flare-up. This was beneficial and as Sharon feels her back  pain is worsening she is inquiring about restarting opioid therapy.";
	var img_caseicon = "ImgCaseStudy-Sharon_thm.jpg";
	var wleft = ((document.width/2)-250);
	var wtop = ((document.height/2)-140);
	var mf = "female";
	var videoIcon = "<img src='../../caseplayer/video.png' width='20' align='left' class='videoIcon'>";
	
	var case_screen = [
	
   	{ val: "0|Step 1 of 6: Stepped Opioid Selection|<br><p class='indentR'>Sharon tells you she would still like to continue to start her opioid therapy but plans on waiting until after the wedding. She is wondering what her options are in terms of drug choice.</p><br><p class='indentLR'>Note: The following list of opioids are specifically addressed by the Guideline and do not necessarily reflect all or newer substances available. </p><br><br><p class='indentLR eg' style='font-weight:bold;'>Click on the appropriate checkbox to select opioids for Sharon. Once you have finished, click the <em>Next Step</em> button at the bottom of the clipboard to continue. </p>|8|Suggest|Feedback|0|Stepped Opioid Selection|0", questions: [
        { val: "Codeine|<p>Yes &ndash; this would be appropriate in Sharon's case.</p>Suggested as a first line treatment for CNCP &ndash;  mild to moderate pain. Use with caution for breast-feeding women: some rapidly  convert codeine to morphine, placing the infant at risk of morphine toxicity.  Lower risk of overdose and addiction than stronger opioids.|0", followup: [] },
        { val: "Tramadol|<p>Yes &ndash; this would be appropriate in Sharon's case.</p>Suggested as a first line treatment for CNCP. Associated with seizures in patients at high seizure risk, or when combined with medications that increase serotonin levels, e.g., SSRIs. Lower risk of overdose and addiction than stronger opioids. |0", followup: [] },
        { val: "Morphine|<p>Yes &ndash; this might be appropriate in Sharon's case.</p><p>Suggested as a second line treatment for CNCP.   Avoid for patients with renal dysfunction: an active metabolite of morphine (M-6 glucoronide) can accumulate to toxic levels in patients with renal impairment.|0", followup: [] },
        { val: "Oxycodone|<p>Yes &ndash; this might be appropriate in Sharon's case.</p><p>Suggested as a second line treatment for CNCP.   Use with caution for patients at higher risk for opioid misuse and addiction: experimental studies and surveys of drug users suggest that oxycodone, hydromorphone and hydrocodone may have a higher abuse liability than morphine.|0", followup: [] },
        { val: "Hydromorphone|<p>Yes &ndash; this might be appropriate in Sharon's case.</p><p>Suggested as a second line treatment for CNCP.   Use with caution for patients at higher risk for opioid misuse and addiction: experimental studies and surveys of drug users suggest that oxycodone, hydromorphone and hydrocodone (not available in Canada) may have a higher abuse liability than morphine.|0", followup: [] },
        { val: "Fentanyl|<p>No &ndash; this is not appropriate in Sharon's case as she is opioid naive.</p><p>1) Before starting fentanyl, obtain a complete history of  opioid use within the last 2 weeks to ensure the patient is fully opioid  tolerant. Tolerance can be assumed if the patient is on a moderate, stable dose  of a strong opioid, i.e., a total daily dose of at least 60&ndash;90 mg/day morphine  equivalence daily for at least 2 weeks. This dose should be scheduled rather  than p.r.n. (at least b.i.d. for CR or q.i.d. for IR). See Supporting Evidence  item 4. </p><p>2) Do not switch from codeine to fentanyl regardless of the  codeine dose, as some codeine users may have little or no opioid tolerance. </p><p>3) Maintain the initial dose for at least 6 days: use extra  caution with patients at higher risk for overdose, e.g., elderly, patients on  benzodiazepines.</p><p>4) Advise the patient as follows:</p><ul>  <li>Be alert for signs of overdose: (e.g. slurred or  drawling speech, emotionally labile, ataxia, nodding off during conversation or  activity) if detected, remove the patch and seek medical attention.</li>  <li>Apply as prescribed: do not apply more than one  patch at a time or change more often than directed.</li>  <li>Avoid heat sources such as heating pads,  electric blankets, saunas, heated waterbeds, hot baths, sunbathing.</li></ul>Dispose of patches securely: a used patch  contains large amount of fentanyl and could be dangerous to others. e.g.,  children or abusers could &quot;recycle&quot; by cutting into small pieces and  sucking the pieces.|0", followup: [] },
        { val: "Methadone|<p>No &ndash; this is not appropriate in Sharon&rsquo;s case.</p><p>Suggested as a third line treatment for severe CNCP pain. </p>Use methadone to treat pain only if holding a  written Health Canada exemption. Titration is hazardous due to its very long  half-life leading to bio-accumulation.|0", followup: [] },
        { val: "Meperidine|<p>NOT recommended for use in CNCP. </p><p>a) oral meperidine has poor bioavailability and is less effective  than codeine, and</p>b)  normeperidine can accumulate with frequent use of parenteral doses of  meperidine, causing seizures and delirium.|0", followup: [] }
   	] },
	
   { val: "0|Step 2 of 6: Feedback|<br><p class='indentLR'>  When considering initiation of an opioid trial always  consider the following step-wise approach:</p><br><h4 class='indentLR'>Table B-8.1 Stepped Approach  to Opioid Selection</h4><table border='1' cellspacing='0' cellpadding='0' width='100%' id='box-table-a'>  <tr><td valign='top'></td><td valign='top'><p><strong>Mild-to-Moderate Pain</strong></p></td><td valign='top'><p><strong>Severe Pain</strong></p></td>  </tr>  <tr><td valign='top'><p><strong>First Line</strong></p></td><td valign='top'><p class='notbold'>codeine or tramadol</p></td><td valign='top'><p class='notbold'>morphine, oxycodone or hydromorphone</p></td>  </tr>  <tr><td valign='top'><p><strong>Second Line</strong></p></td><td valign='top'><p class='notbold'>morphine, oxycodone or hydromorphone</p></td><td valign='top'><p class='notbold'>fentanyl</p></td>  </tr>  <tr><td valign='top'><p><strong>Third Line</strong></p></td><td valign='top'></td><td valign='top'><p class='notbold'>methadone</p></td>  </tr></table><h4 class='indentLR'>Acetaminophen-Opioid  combinations</h4><p class='indentLR'>  Use with caution to avoid acetaminophen toxicity. FDA (U.S.)  recommends a maximum daily dose of 3.2 grams acetaminophen for adults = 10  tablets/day for opioid/ acetaminophen combinations. The manufacturer recommends  a lower dose for tramadol/acetaminophen (8 tablets/day). Heavy drinkers should  be advised to use acetaminophen with extra caution.</p><br><h4 class='indentLR'>CR Formulations</h4>  <p class='indentLR'>  Titrate with caution to avoid overdose and misuse: each CR  tablet can contain a much higher opioid dose than IR formulations, and can  easily be converted to IR by biting or crushing the tablet.</p><br><h4 class='indentLR'>Parenteral Opioids</h4>  <p class='indentLR'>  Parenteral opioids are not recommended for use in CNCP:  parenteral route has higher risk of overdose, abuse and addiction, and  infection.  </p><br><h4 class='indentLR'>Resources:</h4><ul class='indentLR'>  <li><a href=' http://nationalpaincentre.mcmaster.ca/opioid/cgop_b02_r08.html' target='_blank'><span class='has-tip tip-top' data-width='350' title='This is an external link for additional reference purposes only. The site and/or content is not part of this Mainpro/Maincert accredited program. It will open in a new window.'>R08.  Recommendation Statement</span></a></li>  <li><a href='http://nationalpaincentre.mcmaster.ca/opioidmanager/' target='_blank'><span class='has-tip tip-top' data-width='350' title='This is an external link for additional reference purposes only. The site and/or content is not part of this Mainpro/Maincert accredited program. It will open in a new window.'>Opioid  Manager &trade;</span></a></li></ul>|1|||0|Feedback|0", questions: [{ val: "null||0", followup: [] }] },
	
   { val: "0|Step 3 of 6: Optimal Dose: Select Initial and Incremental Dose|<br><p class='indentLR'>Sharon wishes to minimize her drug consumption and have the least amount of side effects. She knows she has tolerated acetaminophen with codeine  in the past. Acetaminophen consumption and appropriate dosing of short-acting  opioid therapy was discussed. Sharon tells you that her pain is the worst first thing in the morning, at the end of her work day, and before bed. </p><br><p class='indentLR'>  The object of Sharon's opioid trial is to determine the  <strong>optimal dose</strong>, i.e., a dose that will improve function or reduce pain intensity  by at least 30% without causing major adverse effects or complications. It is  recommended to start the opioid trial with a low dose and increase the dose in  small quantities. Opioids produce a graded analgesic response: the patient  experiences the greatest benefits at lower doses and a plateauing of analgesic  response at higher doses. Therefore, slow titration 1) avoids unnecessarily  high doses, and 2) reduces the risk of sedation and overdose as it ensures that  a dose increase does not exceed the patient's tolerance. </p><br><p class='indentLR'>  The optimal dose is reached with a balance of three factors:</p><br><ul class='indentLR'>  <li><strong>Effectiveness:</strong> improved function or at least  30% reduction in pain intensity</li>  <li><strong>Plateauing:</strong> effectiveness plateaus &mdash; increasing  the dose yields negligible benefit</li>  <li><strong>Adverse effects/complications:</strong> adverse effects  or complications are manageable.</li></ul>|5|Opioid|Dosage Info|0|Optimal Dose|0", questions: [
        { val: "Codeine|<table border='1' cellspacing='0' cellpadding='0' id='box-table-a'>  <tr>    <td width='25%' valign='top'><strong>Initial dose</strong></td>    <td width='25%' valign='top'><strong>Minimum time interval for increase</strong></td>    <td width='25%' valign='top'><strong>Suggested dose increase</strong></td>    <td width='25%' valign='top'><strong>Minimum daily dose before converting IR to CR</strong></td>  </tr></table>|2", followup: [
			{ val: "Alone or in combination with acetaminophen or ASA|<table border='1' cellspacing='0' cellpadding='0' id='box-table-a'>  <tr>    <td width='25%' valign='top'><p>15-30 mg<br>q.4 h. as required</p></td>    <td width='25%' valign='top'><p>7 days</p></td>    <td width='25%' valign='top'><p>15-30 mg/day up to maximum of<br>      600 mg/day (acetaminophen dose should not exceed 3.2    grams/day)</p></td>    <td width='25%' valign='top'><p>100 mg daily</p></td>  </tr></table>"},
       		{ val: "Controlled release|<table border='1' cellspacing='0' cellpadding='0' id='box-table-a'><tr><td width='25%' valign='top'><p>50 mg q.12 h.</p></td><td width='25%' valign='top'><p>2 days</p></td><td width='25%' valign='top'><p>50 mg/day up to maximum of 300 mg q.12 h.</p></td><td width='25%' valign='top'><p>NA</p></td>  </tr></table>"}
		] },
        { val: "Tramadol|<table border='1' cellspacing='0' cellpadding='0' id='box-table-a'>  <tr>    <td width='25%' valign='top'><strong>Initial dose</strong></td>    <td width='25%' valign='top'><strong>Minimum time interval for increase</strong></td>    <td width='25%' valign='top'><strong>Suggested dose increase</strong></td>    <td width='25%' valign='top'><strong>Minimum daily dose before converting IR to CR</strong></td>  </tr></table>|2", followup: [
			{ val: "Tramadol (37.5 mg) + acetaminophen (325 mg)|<table border='1' cellspacing='0' cellpadding='0' id='box-table-a'><tr><td width='25%' valign='top'><p>1 tablet<br>q.4-6 h. as needed up to 4/day</p></td><td width='25%' valign='top'><p>7 days</p></td><td width='25%' valign='top'><p>1-2 tab q. 4-6 h. as needed up to maximum 8 tablets/day</p></td><td width='25%' valign='top'><p>3 tablets</p></td>  </tr></table>"},
       		{ val: "Controlled release|<table border='1' cellspacing='0' cellpadding='0' id='box-table-a'><tr><td width='25%' valign='top'><p>&nbsp;</p></td><td width='25%' valign='top'><p>&nbsp;</p></td><td width='25%' valign='top'><p><strong>Maximum Doses:</strong></p></td><td width='25%' valign='top'><p>&nbsp;</p></td>  </tr></table><table border='1' cellspacing='0' cellpadding='0' id='box-table-a'><tr><td width='25%' valign='top'><p><strong>a)</strong> Zytram XL<sup>&reg;</sup>:<br>150 mg q. 24 h.</p></td><td width='25%' valign='top'><p>7 days</p></td><td width='25%' valign='top'><p>400 mg/day</p></td><td width='25%' valign='top'><p>NA</p></td>  </tr></table><table border='1' cellspacing='0' cellpadding='0' id='box-table-a'><tr><td width='25%' valign='top'><p><strong>b)</strong> Tridural&trade;:<br>100 mg q. 24 h.</p></td><td width='25%' valign='top'><p>2 days</p></td><td width='25%' valign='top'><p>300 mg/day</p></td><td width='25%' valign='top'><p>NA</p></td>  </tr></table><table border='1' cellspacing='0' cellpadding='0' id='box-table-a'><tr><td width='25%' valign='top'><p><strong>c)</strong> Ralivia&trade;:<br>100 mg q. 24 h.</p></td><td width='25%' valign='top'><p>5 days</p></td><td width='25%' valign='top'><p>300 mg/day</p></td><td width='25%' valign='top'><p>NA</p></td>  </tr></table>"}
		] },
        { val: "Morphine|<table border='1' cellspacing='0' cellpadding='0' id='box-table-a'>  <tr>    <td width='25%' valign='top'><strong>Initial dose</strong></td>    <td width='25%' valign='top'><strong>Minimum time interval for increase</strong></td>    <td width='25%' valign='top'><strong>Suggested dose increase</strong></td>    <td width='25%' valign='top'><strong>Minimum daily dose before converting IR to CR</strong></td>  </tr></table>|2", followup: [
			{ val: "Immediate release|<table border='1' cellspacing='0' cellpadding='0' id='box-table-a'><tr><td width='25%' valign='top'><ul type='disc'>  <li>5-10 mg<br>q. 4 h. as needed</li>  <li>maximum 40 mg/day</li></ul></td><td width='25%' valign='top'><p>7 days</p></td><td width='25%' valign='top'><p>5-10 mg/day</p></td><td width='25%' valign='top'><p>20-30 mg</p></td>  </tr></table>"},
       		{ val: "Controlled release|<table border='1' cellspacing='0' cellpadding='0' id='box-table-a'><tr><td width='25%' valign='top'><ul type='disc'>  <li>10-30 mg q.12 h.</li>  <li>Kadian<sup>&reg;</sup>:<br>q. 24 h.</li></ul><p>Kadian<sup>&reg;</sup> should not be started in opioid-naive patients.</p></td><td width='25%' valign='top'><p>Minimum 2 days, recommended: 14 days</p></td><td width='25%' valign='top'><p>5-10 mg/day</p></td><td width='25%' valign='top'><p>NA</p></td>  </tr></table>"}
		] },
        { val: "Oxycodone|<table border='1' cellspacing='0' cellpadding='0' id='box-table-a'>  <tr>    <td width='25%' valign='top'><strong>Initial dose</strong></td>    <td width='25%' valign='top'><strong>Minimum time interval for increase</strong></td>    <td width='25%' valign='top'><strong>Suggested dose increase</strong></td>    <td width='25%' valign='top'><strong>Minimum daily dose before converting IR to CR</strong></td>  </tr></table>|2", followup: [
			{ val: "Immediate release|<table border='1' cellspacing='0' cellpadding='0' id='box-table-a'><tr><td width='25%' valign='top'><ul type='disc'>  <li>5-10 mg<br>q. 6 h. as needed</li>  <li>maximum 30 mg/day</li></ul></td><td width='25%' valign='top'><p>7 days</p></td><td width='25%' valign='top'><p>5 mg/day</p></td><td width='25%' valign='top'><p>20 mg</p></td>  </tr></table>"},
       		{ val: "Controlled release|<table border='1' cellspacing='0' cellpadding='0' id='box-table-a'><tr><td width='25%' valign='top'><ul type='disc'>  <li>10-20 mg q.12 h.</li>  <li>maximum 30 mg/day</li></ul></td><td width='25%' valign='top'><p>Minimum 2 days, recommended: 14 days</p></td><td width='25%' valign='top'><p>10 mg/day</p></td><td width='25%' valign='top'><p>NA</p></td>  </tr></table>"}
		] },
        { val: "Hydromorphone|<table border='1' cellspacing='0' cellpadding='0' id='box-table-a'>  <tr>    <td width='25%' valign='top'><strong>Initial dose</strong></td>    <td width='25%' valign='top'><strong>Minimum time interval for increase</strong></td>    <td width='25%' valign='top'><strong>Suggested dose increase</strong></td>    <td width='25%' valign='top'><strong>Minimum daily dose before converting IR to CR</strong></td>  </tr></table>|2", followup: [
			{ val: "Immediate release|<table border='1' cellspacing='0' cellpadding='0' id='box-table-a'><tr><td width='25%' valign='top'><ul type='disc'>  <li>1-2 mg<br>q. 4-6 h. as needed</li>  <li>maximum 8 mg/day</li></ul></td><td width='25%' valign='top'><p>7 days</p></td><td width='25%' valign='top'><p>1-2 mg/day</p></td><td width='25%' valign='top'><p>6 mg</p></td>  </tr></table>"},
       		{ val: "Controlled release|<table border='1' cellspacing='0' cellpadding='0' id='box-table-a'><tr><td width='25%' valign='top'><ul type='disc'>  <li>3 mg q.12 h.</li>  <li>maximum 9 mg/day</li></ul></td><td width='25%' valign='top'><p>Minimum 2 days, recommended: 14 days</p></td><td width='25%' valign='top'><p>2-4 mg/day</p></td><td width='25%' valign='top'><p>NA</p></td>  </tr></table>"}
		] }
   	] },
	
	{ val: "0|Step 4 of 6: Optimal Dose: Measure Opioid Effectiveness|<br><p class='indentLR'>Sharon is scheduled to see you later today to discuss her opioid trial. Taking into consideration the above information and treatment goals, you must decide whether her opioid trial was successful.</p><br><p class='indentLR'>You decide to assess Sharon’s functional changes and any adverse effects by asking her some questions.  </p>|2|Suggest|Feedback|0|Optimal Dose: Measure Opioid Effectiveness|0", questions: [
        { val: "Ask Sharon about her therapeutic goals, improvements in sleep, work, overall function, ADLs, etc.|<p>&quot;My sleep has improved - I'm now getting close to 6 hours.  Unfortunately, my pain continues to interfere with my ability to work full  time. I have only used my lorazepam 3  times in the last 3 weeks when I was anxious regarding work and social  stressors.</p><p>I'm wondering if I can take a dose in the middle of the day?  I think this might help me to better function at work as I find my pain relief  doesn't last for the whole day.</p><p>Overall my pain scores remain high at about 8/10  several times throughout the day. After a dose of medication my pain scores  decrease to 4-5/10 but I don't find it lasts the whole 4-6hrs.&quot;</p>|0", followup: [] },
        { val: "Are you experiencing any side effects?|&quot;Well, I've been having some constipation.&quot;|0", followup: [] }
   	] },
	
   { val: "0|Step 5 of 6: Feedback|<br><div class='indentLR'><p>Sharon has seen some improvement in her identified goal of being  able to do grocery shopping without &ldquo;looking like an old lady.&rdquo; Now that Sharon  is noticing an improvement in pain scores she has prioritized sleep and  function at work as more important and would like to improve upon these new,  more realistic goals.</p><p>  <strong>Note:</strong> the  <a href='http://nationalpaincentre.mcmaster.ca/opioid/cgop_b_app_b09.html' target='_blank'><span class='has-tip tip-top' data-width='350' title='This is an external link for additional reference purposes only. The site and/or content is not part of this Mainpro/Maincert accredited program. It will open in a new window.'>Brief Pain Inventory</span></a> is an example of a structured assessment tool frequently used to  assess a patient&rsquo;s functional changes.</p><h4>Resources:</h4><ul>  <li><a href='http://nationalpaincentre.mcmaster.ca/opioid/cgop_b02_r08.html' target='_blank'><span class='has-tip tip-top' data-width='350' title='This is an external link for additional reference purposes only. The site and/or content is not part of this Mainpro/Maincert accredited program. It will open in a new window.'>R08.  Recommendation Statement</span></a></li>  <li><a href='http://nationalpaincentre.mcmaster.ca/opioid/cgop_b_app_b09.html' target='_blank'><span class='has-tip tip-top' data-width='350' title='This is an external link for additional reference purposes only. The site and/or content is not part of this Mainpro/Maincert accredited program. It will open in a new window.'>Appendix  B-9: Brief Pain Inventory</span></a></li>  <li><a href='http://nationalpaincentre.mcmaster.ca/opioidmanager/' target='_blank'><span class='has-tip tip-top' data-width='350' title='This is an external link for additional reference purposes only. The site and/or content is not part of this Mainpro/Maincert accredited program. It will open in a new window.'>Opioid  Manager &trade;</span></a></li></ul></div>|1|||0|Feedback|0", questions: [{ val: "null||0", followup: [] }] },
	
   	{ val: "2|Step 6 of 6: REVIEW|<p class='indentLR'>Suggested review of the case pertaining to Management of Sharon. During this case, you have made several choices. The choices you have made are indicated by an arrow.</p><br>|1|||0||0", questions: [
        { val: "" }
   	] }
	];